const csvURL="https://docs.google.com/spreadsheets/d/e/2PACX-1vTBtyGriDud4pVArvyGHpC3aptGso3l6xn2B8phOwMIn2JekjQZPPkKzt2274D82ie1djrwndV6PcFC/pub?gid=481332784&single=true&output=csv";
const REFRESH_MS=5*60*1000,medals=["🥇","🥈","🥉","🏅"],classes=["first","second","third","fourth"],ordinal=["1st place","2nd place","3rd place","4th place"];
const cleanMoney=v=>Number(String(v??"").replace(/[^0-9.-]/g,""))||0;
const currency=v=>v.toLocaleString("en-US",{style:"currency",currency:"USD",minimumFractionDigits:2});
function formatTimestamp(v){if(!v)return"Not yet recorded";const d=new Date(v);if(Number.isNaN(d.getTime()))return v;const n=new Date(),same=d.toDateString()===n.toDateString();return`${same?"Today":d.toLocaleDateString("en-US",{month:"short",day:"numeric",year:"numeric"})} • ${d.toLocaleTimeString("en-US",{hour:"numeric",minute:"2-digit"})}`}
function setStatus(t,e=false){const s=document.getElementById("status");s.querySelector("span:last-child").textContent=t;s.classList.toggle("error",e)}
function esc(v){return String(v).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]))}
async function loadLeaderboard(){const cards=document.getElementById("cards"),updated=document.getElementById("updated"),banner=document.getElementById("leader-banner");setStatus("Refreshing");
try{const r=await fetch(`${csvURL}&cacheBust=${Date.now()}`,{cache:"no-store"});if(!r.ok)throw new Error(`Google Sheets returned ${r.status}`);const parsed=Papa.parse(await r.text(),{header:true,skipEmptyLines:true,transformHeader:h=>h.trim()});
let p=parsed.data.map(row=>({name:String(row.Child??row.Name??"").trim(),balance:cleanMoney(row.Balance),rank:Number(row.Rank)||null,medal:String(row.Medal??"").trim(),updated:String(row["Last Updated"]??"").trim()})).filter(x=>x.name);if(!p.length)throw new Error("No participant rows were found.");p.sort((a,b)=>a.rank&&b.rank?a.rank-b.rank:b.balance-a.balance);
const leader=p[0],second=p[1];banner.querySelector(".leader-name").textContent=leader.name;banner.querySelector(".leader-balance").textContent=currency(leader.balance);banner.querySelector(".leader-margin").textContent=second?`+${currency(leader.balance-second.balance)} ahead of 2nd`:"";
cards.innerHTML=p.slice(0,4).map((x,i)=>`<article class="card ${classes[i]}" style="animation-delay:${i*60}ms"><div class="place">${x.medal||medals[i]}</div><div><div class="rank">${ordinal[i]}</div><div class="name">${esc(x.name)}</div></div><div class="money"><div class="balance">${currency(x.balance)}</div>${i===0?'<div class="behind leader">👑 Currently leading</div>':`<div class="behind">▼ ${currency(leader.balance-x.balance)} behind</div>`}</div></article>`).join("");
updated.textContent=formatTimestamp(p.find(x=>x.updated)?.updated||"");setStatus("Live")}catch(e){console.error(e);cards.innerHTML=`<div class="error-card"><strong>Unable to load the leaderboard</strong><div>${esc(e.message)}</div></div>`;banner.querySelector(".leader-name").textContent="Data unavailable";banner.querySelector(".leader-balance").textContent="";banner.querySelector(".leader-margin").textContent="";updated.textContent="Unavailable";setStatus("Connection error",true)}}
loadLeaderboard();setInterval(loadLeaderboard,REFRESH_MS);document.addEventListener("visibilitychange",()=>{if(!document.hidden)loadLeaderboard()});if("serviceWorker"in navigator)window.addEventListener("load",()=>navigator.serviceWorker.register("service-worker.js"));
